### ISSUE TITLE
Add a 'PR Would Be Accepted' or 'Help Wanted' label to the Issue Tracker

### ISSUE THREAD

**Issue by webmaven** [morepath/morepath#178]
Like here: 
- [ ] https://github.com/kennethreitz/python-guide/labels
- [ ] https://github.com/maxogden/dat/labels

Some alternate label sets to consider for inspiration, but don't go crazy ;-) :
- [ ] https://github.com/kennethreitz/requests/labels
- [ ] https://github.com/gittip/www.gittip.com/labels
- [ ] https://github.com/balanced/balanced-dashboard/labels

These are probably going crazy:
- [ ] https://github.com/GoogleCloudPlatform/endpoints-proto-datastore/labels
- [ ] https://github.com/project-open-data/project-open-data.github.io/labels
